# Borrowed from
# https://github.com/pfisterer/edsc-microk8s-playbook/blob/master/roles/microk8s/tasks/main.yaml
# ----------------------------------------------------------
# Workaround to be able to connect to microk8s remotely
# https://github.com/ubuntu/microk8s/issues/421
# ----------------------------------------------------------
---
- name: Check IP is already included in the template
  shell: "cat /var/snap/microk8s/current/certs/csr.conf.template | grep '= {{ansible_host}}' | wc -l"
  register: ip_included
  changed_when: False

- name: Get highest entry in the list of IPs (conf)
  shell: "cat /var/snap/microk8s/current/certs/csr.conf | sed -nr 's/IP\\.([0-9]+).*/\\1/p' | sort | tail -n 1"
  register: csr_output
  when: ip_included.stdout_lines[0]|int == 0

- name: Get highest entry in the list of IPs (template)
  shell: "cat /var/snap/microk8s/current/certs/csr.conf.template | sed -nr 's/IP\\.([0-9]+).*/\\1/p' | sort | tail -n 1"
  register: csr_template_output
  when: ip_included.stdout_lines[0]|int == 0

- name: Add IP entry
  lineinfile:
    path: /var/snap/microk8s/current/certs/csr.conf.template
    insertafter: "^IP.{{csr_template_output.stdout_lines[0]}} = .*"
    line: "IP.{{csr_output.stdout_lines[0]|int + 1}} = {{ansible_host}}"
  register: csr_mod_result
  when: ip_included.stdout_lines[0]|int == 0

- name: Restart microk8s (stop)
  shell: "microk8s.stop"
  when: ip_included.stdout_lines[0]|int == 0

- name: Restart microk8s (start)
  shell: "microk8s.start"
  when: ip_included.stdout_lines[0]|int == 0
  ignore_errors: True

- name: Wait for microk8s to be ready after updating the CSR
  shell: "microk8s status --wait-ready"
  changed_when: False
  when: ip_included.stdout_lines[0]|int == 0
