apiVersion: v1
kind: Namespace
metadata:
  name: replaybot-preprod
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: replaybot-preprod
spec:
  ports:
  - port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  name: parser
  namespace: replaybot-preprod
spec:
  ports:
  - port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    app: parser
---
apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: replaybot-preprod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5002
  selector:
    app: search
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: discord
  name: discord
  namespace: replaybot-preprod
spec:
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
      - env:
        - name: NEW_RELIC_APP_NAME
          value: replaybot_discord_preprod
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: NEW_RELIC_LICENSE_KEY
              name: replaybot-secrets
        - name: BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: BOT_TOKEN
              name: replaybot-secrets
        - name: BOT_SHARED_KEY
          valueFrom:
            secretKeyRef:
              key: BOT_SHARED_KEY
              name: replaybot-secrets
        - name: PARSER_ENDPOINT
          value: http://parser:5001
        - name: API_ENDPOINT
          value: https://api-preprod.replaybot.com/api
        image: leigholiver/replaybot_discord_preprod
        name: discord
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elasticsearch
  name: elasticsearch
  namespace: replaybot-preprod
spec:
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - env:
        - name: discovery.type
          value: single-node
        - name: bootstrap.memory_lock
          value: "true"
        - name: ES_JAVA_OPTS
          value: -Xms128m -Xmx128m
        image: elasticsearch:7.7.0
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
      initContainers:
      - command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        image: busybox:1.27.2
        name: init-sysctl
        securityContext:
          privileged: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: parser
  name: parser
  namespace: replaybot-preprod
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
      - env:
        - name: NEW_RELIC_APP_NAME
          value: replaybot_parser_preprod
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: NEW_RELIC_LICENSE_KEY
              name: replaybot-secrets
        image: leigholiver/replaybot_parser_preprod
        name: parser
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: 150m
            memory: 300Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search
  name: search
  namespace: replaybot-preprod
spec:
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - env:
        - name: NEW_RELIC_APP_NAME
          value: replaybot_search_preprod
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: NEW_RELIC_LICENSE_KEY
              name: replaybot-secrets
        - name: ELASTICSEARCH_ENDPOINT
          value: http://elasticsearch:9200
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              key: ELASTICSEARCH_PASSWORD
              name: replaybot-secrets
        image: leigholiver/replaybot_search_preprod
        name: search
        ports:
        - containerPort: 5002
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: search-preprod.replaybot.com
  name: search
  namespace: replaybot-preprod
spec:
  rules:
  - host: search-preprod.replaybot.com
    http:
      paths:
      - backend:
          service:
            name: search
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - search-preprod.replaybot.com
    secretName: search-tls
