apiVersion: apps/v1
kind: Deployment
metadata:
  name: parser
  namespace: replaybot-legacy
  labels:
    app: parser
spec:
  selector:
    matchLabels:
      app: parser
  template:
    metadata:
      labels:
        app: parser
    spec:
      containers:
        - name: parser
          image: leigholiver/replaybot_parser
          env:
            - name: NEW_RELIC_APP_NAME
              value: replaybot_parser
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: replaybot-secrets
                  key: NEW_RELIC_LICENSE_KEY
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: parser
  namespace: replaybot-legacy
spec:
  selector:
    app: parser
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
