---
- name: install cert-manager
  shell: microk8s kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.yaml

- name: write cert-manager manifest
  template:
    src: ../templates/cert-manager.yml
    dest: $PWD/cert-manager.yml

- name: apply cert-manager manifest
  shell: microk8s kubectl apply -f $PWD/cert-manager.yml
  # todo: failed calling webhook \"webhook.cert-manager.io\" connection refused?
  retries: 5
  delay: 10
  register: result
  until: result.rc == 0

- name: remove tmp cert-manager manifest
  file:
    path: $PWD/cert-manager.yml
    state: absent
