---
- name: write example manifest
  template:
    src: ../templates/example.yml
    dest: $PWD/example.yml

- name: apply example manifest
  shell: "{{ engine }} kubectl apply -f $PWD/example.yml"
  when: deploy_example
