---
- name: write externaldns manifest
  template:
    src: ../templates/externaldns.yml
    dest: $PWD/externaldns.yml

- name: apply externaldns manifest
  shell: "{{ engine }} kubectl apply -f $PWD/externaldns.yml"

- name: remove tmp externaldns manifest
  file:
    path: $PWD/externaldns.yml
    state: absent
