---
- name: write flux manifest
  template:
    src: ../templates/flux.yml
    dest: $PWD/flux.yml

- name: apply flux manifest
  shell: "{{ engine }} kubectl apply -f $PWD/flux.yml"

- name: remove tmp flux manifest
  file:
    path: $PWD/flux.yml
    state: absent
